# Generated by Django 4.2.29 on 2026-04-30 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odds', models.DecimalField(decimal_places=2, max_digits=6)),
                ('play_time', models.TimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_odds', models.DecimalField(decimal_places=2, default=1.2, max_digits=6)),
                ('max_odds', models.DecimalField(decimal_places=2, default=11.0, max_digits=6)),
                ('min_seconds_ahead', models.IntegerField(default=30)),
                ('max_seconds_ahead', models.IntegerField(default=300)),
                ('timezone', models.CharField(default='Africa/Dar_es_Salaam', max_length=64)),
            ],
            options={
                'verbose_name': 'Prediction Settings',
            },
        ),
    ]
