# Generated by Django 4.2.29 on 2026-05-03 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorRoundOdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(blank=True, null=True)),
                ('payout', models.DecimalField(decimal_places=2, max_digits=12)),
                ('raw_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Monitor Round Odds',
                'verbose_name_plural': 'Monitor Round Odds',
            },
        ),
    ]
