services:
  - type: web
    name: aviator-backend-web
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: bash start.sh
    autoDeploy: true
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: aviator-backend-db
          property: connectionString

  - type: worker
    name: aviator-backend-monitor
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py run_monitor_worker
    autoDeploy: true
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: aviator-backend-db
          property: connectionString

databases:
  - name: aviator-backend-db
    plan: free
